config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :transcripts, only: [:create]
    end
  end

  resources :transcripts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transcript.rb
class Transcript < ApplicationRecord
  belongs_to :user, optional: true

  mount_uploader :audio_file, AudioFileUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transcripts

  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/transcripts_controller.rb
class Api::V1::TranscriptsController < ApplicationController
  def create
    temp_audio_file_path = params["recording"].tempfile.path
    output = %x(python lib/python/speech_to_text_2.1/run.py "#{temp_audio_file_path}")
    transcripts = JSON.parse(output)
    original = transcripts["original"].rstrip + "."
    simple = transcripts["simple"].rstrip + "."
    original[0] = original[0].capitalize
    simple[0] = simple[0].capitalize

    if current_user
      new_transcript = Transcript.new
      new_transcript.user = current_user
      new_transcript.audio_file = params["recording"].tempfile
      new_transcript.original = original
      new_transcript.simplified = simple
      new_transcript.save
    end

    render json: {
      original: render_transcript(original),
      simplified: render_transcript(simple)
    }, status: :created
  end

  private

  def render_transcript(transcript)
    ApplicationController.render(partial: 'transcripts/transcript', locals: { transcript: transcript })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/transcripts_controller.rb
class TranscriptsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @transcripts = current_user.transcripts.order(created_at: :desc)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="col-md-12 alert-disappear">
      <div class="alert alert-danger">
        <ul>
          #{messages}
        </ul>
      </div>
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTalk</title>
    <meta name="viewport" content="initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-info alert-dismissible main-alerts" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible main-alerts" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if !current_page?(root_path) && !request.path.include?("/welcome/index") %>
            <a class="navbar-brand" href="<%= root_path %>">SimpleTalk</a>
          <% end %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown user-nav-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  My Account <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-left">
                  <li><%= link_to "My Transcripts", transcripts_path %></li>
                  <li><%= link_to "Edit Account", edit_user_registration_path %></li>
                </ul>
              </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/transcripts/_transcript.html.erb
<%= transcript.html_safe %>

app/views/transcripts/index.html.erb
<div class="container">
  <div class="row transcripts-index">
    <div class="col-md-12 text-center">
      <h2 id="my-transcripts-title">My Transcripts</h2>
    </div>

    <% @transcripts.each do |transcript| %>
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading text-center">
            <h3 class="panel-title"><%= transcript.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y %l:%M:%S %p") %></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-6 text-center">
                <h3>Orginal</h3>
                <p><%= transcript.original.html_safe %></p>
              </div>
              <div class="col-md-6 text-center">
                <h3>Simple</h3>
                <p><%= transcript.simplified %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/translations/index.html.erb
<div class="container">
  <div class="row">
    <% @translations.each do |translation| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= translation.created_at %></h3>
        </div>
        <div class="panel-body">
          
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="alert alert-danger text-center" id="browser-alert" role="alert"></div>
<div class="container welcome-screen">
  <div class="row text-center">
    <div class="col-md-12">
      <h1>SimpleTalk</h1>
    </div>

    <div class="col-md-4 col-md-push-4 controls-div">
      <div class="mic-btn">
        <%= link_to "#" do %>
          <%= image_tag("/microphone.png", size: "200") %>
        <% end %>
      </div>

      <%= link_to "#" do %>
        <div class="red-dot"></div>
        <div class="recording-dot"></div>
      <% end %>

      <div class="stop-btn-div">
        <%= link_to "Stop", "#", class: "btn btn-danger", id: "stop-btn" %>
      </div>

      <div class="edit-btn-div">
        <%= link_to "Edit", "#", class: "btn btn-primary", id: "edit-btn" %>
      </div>
    </div>

    <div class="col-md-4 col-md-pull-4">
      <div class="transcript-box jargon">
        <h2>Orginal</h2>
        <h3 class="transcript"></h3>
      </div>
    </div>

    <div class="col-md-4">
      <div class="transcript-box laymans">
        <h2>Simple</h2>
        <h3 class="transcript"></h3>
      </div>
    </div>

    <div class="col-md-4 edit-box">
      <div class="transcript-box laymans-edit">
        <textarea></textarea>
      </div>
    </div>
  </div>
</div>